## Travis CI Integration
language: c
install:
  - sudo apt-get update -qq > /dev/null
  - sudo apt-get install -qq mono-devel mono-gmcs > /dev/null
script:
  - cd ContinuosIntegrationWithTravis
  - ls -a
  - xbuild ContinuosIntegrationWithTravis.sln
  - cd bin
  - ls -a
branches: master
