## Travis CI Integration
language: c
install:
  - sudo apt-get install mono-devel mono-gmcs
script:
  - cd ContinuosIntegrationWithTravis
  - ls -a
  - xbuild ContinuosIntegrationWithTravis.sln
  - cd bin
  - ls -la
  - ls -a
branches: master
